### ISSUE TITLE
what is insecure about jwt?

### ISSUE THREAD

**Issue by cryptix** [hako/branca#1]
sorry for this naive question but could you add a sentence or reference link about why JWT is insecure?

**Comment by tuupola** [comment]
https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid

TL;DR it is easy to shoot yourself in the foot with JWT. Yes it is possible to implement JWT in secure way by removing some of the features, but then you are not really using JWT anymore. 

Examples of practical attacks.

https://blog.websecurify.com/2017/02/hacking-json-web-tokens.html
https://hackernoon.com/can-timing-attack-be-a-practical-security-threat-on-jwt-signature-ba3c8340dea9
https://www.notsosecure.com/crafting-way-json-web-tokens/

Good example of vulnerability caused by the spec. Fixed by removing support for `none` alg. This has now been fixed in most libraries.

https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by cryptix** [comment]
Thanks @tuupola! I knew about the none alg thing and will review this some more.

Leaving this open for visibility - feel free to close it when ever you see fit @hako!
