### ISSUE TITLE
Need a method to get the timestamp from a Token string

### ISSUE THREAD

**Issue by SaulDoesCode** [hako/branca#5]
I want to refresh tokens every other day before they expire, to do this I'll probably need to get a timestamp from the token string somehow. The decoder doesn't expose this information, I'm hoping you'll perhaps add a method to get the timestamp alongside the payload.

maybe something like this
```go
type Token struct {
   Timestamp time.Time
   Payload string
}

tkn, err := branca.DecodeToken(token) // -> Token, error

// what I want to do
if closeToExpiration(tkn.Timestamp) {
   refreshTokenAndUpdateDB(
      UserIdFromPayload(tkn.Payload)
   )
}
```

**Comment by SaulDoesCode** [comment]
Oh, another thing that might be useful: [expose the errors like @dwin did.](https://github.com/dwin/branca/commit/79be4d7c3d1c47ceb24f26048c8760daabc5a96f)

**Comment by hako** [comment]
Nice idea, but I see you have already made some of the suggested changes on your branch, I would be happy to merge it in, as long as they pass the tests. :)

**Comment by zia-newversion** [comment]
Interesting. This is indeed useful.

However, I have a different take on the issue. I would rather this package not implement a separate `Token` struct but instead provide methods for manually getting/setting Timestamp while decoding/encoding. e.g.

```go
// Currently:
se, err = branca.EncodeToString(sd)
sd, err = branca.DecodeToString(se)

// I propose:
se, err = branca.EncodeToString(sd, ts) // string, time.Time -> string, error
sd, ts, err = branca.DecodeToString(se) // string -> string, time.Time, error

// Or different, new methods, if we want to avoid breaking existing code:
se, err = branca.EncodeWithTimestamp(sd, ts)
sd, ts, err = branca.DecodeWithTimestamp(se, ts)
```

Although packing `se` into a `struct` does roughly the same job, that's an extra type we don't really need. There may a non-zero (maybe insignificant, but not zero) overhead for destructuring the proposed `type Token` into values for further consumption.

Also, the proposal does not provide a way to _set_ the timestamp at encoding. Right now, the timestamp is automatically set to `time.Now().Unix()` and that works for most purposes. But in some use cases, you may want to set it yourself, e.g. set the timestamp to when the request for when (1) a token was initiated, rather than when (2) the encoding function call was made, when the difference between (1) and (2) may be measurable to upto ±0.5s, which can easily happen when there's password hashing or db access between (1) and (2).

And unrelated to the current issue, IMO we really need versions of the Encode/Decode methods that work with `io.Reader`/`io.Writer` and/or byte-slices. I see something like this is already on the TODO list, and I may get around to creating a PR soon, if no one has already taken it up.
